MODEL:
  OUTPUT_DIR: timbre_recognition/models/inception_resnet_v2/esc-50/ckpts/
  CONV_BODY: inception_v4
  NUM_CLASSES: 50
  EMBED_DIM: 128
TRAIN:
  TRAINING: True
  BATCH_SIZE: 32
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 2000
  NUM_EPOCHS: 800
DATASET:
  BUFFER_SIZE: 200
  PATH: timbre_recognition/datasets/ESC-50/audio/
EVALUATE:
  THRESHOLD: 0.5