MODEL:
  OUTPUT_DIR: timbre_recognition/models/inception_resnet_v2/esc50
  CONV_BODY: inception_v4
  NUM_CLASSES: 50
  EMBED_DIM: 64
TRAIN:
  TRAINING: True
  BATCH_SIZE: 64
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 2000
  NUM_EPOCHS: 200
DATASET:
  BUFFER_SIZE: 200